console.log("My name is memuna gul");
console.log("Gul is here..");
console.log("new");
console.log("My name is memuna gul");
console.log("Gul is here..");
console.log("new");
console.log("My name is memuna gul");
console.log("Gul is here..");
console.log("new");
console.log("My name is memuna gul");
console.log("Gul is here..");
console.log("new");